version: '3'
services: 
  adminv2: 
    image: mkhang123/adminbe:latest
    volumes:
      - ./BE:/usr/src/app
    networks: 
      - backend
    environment:
      - MYSQL_HOST=66.42.59.144
      - MYSQL_USER=lucifer
      - MYSQL_PASS=12344321
      - MYSQL_DB=moviedb
    ports: 
      - 2222:9999
  frontendv2:
    image: mkhang123/frontend:latest
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 4000:3000
    stdin_open: true
    networks: 
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
networks: 
  backend:
